CLASS ZCL_AMDP_DEMO DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    INTERFACES IF_AMDP_MARKER_HDB.

    CLASS-METHODS MULTIPLY_SIMPLE
      IMPORTING
        VALUE(IV_CLIENT)  TYPE MANDT
        VALUE(IV_NUMBER1) TYPE I
        VALUE(IV_NUMBER2) TYPE I
      EXPORTING
        VALUE(EV_RETURN)  TYPE I.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_AMDP_DEMO IMPLEMENTATION.
  METHOD MULTIPLY_SIMPLE BY DATABASE PROCEDURE
 FOR HDB
 LANGUAGE SQLSCRIPT
 OPTIONS READ-ONLY.

    ev_return = iv_number1 * iv_number2;

  ENDMETHOD.

ENDCLASS.